backend:
  name: github
  repo: kyndream/middleman-boilerplate-blog
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "images/uploads" # folder where use uploaded files should go

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "source/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true # prevents users from deleting items in a collection
    extension: markdown
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog_show"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
